batch_size: 1 # 8
device_id: 0
num_workers: 1
prefetch_factor: 8
max_epochs: 50
lr: 0.0005 # 0.0005
weight_decay: 0.0001
milestones: [ 10, 20, 30, 40 ]
gamma: 0.5
clip_grad_value: 5
accumulation_steps: 8
save_freq: 10
model_param_filename: "model_parameters.pt"

pretrain_ckpt: ""

train_mode: finetune
use_reference_bank: true

checkpoint_ratios:
  - 1.0

append_relative_time: true